// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.1
// source: proto/xiaov.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 基础消息 ==========
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_xiaov_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ========== 聊天请求 ==========
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID（必填）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 用户发送的消息（必填）
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID（可选，用于保持上下文）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_xiaov_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ========== 聊天响应 ==========
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                  // 状态码：0-成功，其他-失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // 状态描述
	Reply         string                 `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`                                                                                 // 助手回复的消息
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                        // 会话ID
	Intent        string                 `protobuf:"bytes,5,opt,name=intent,proto3" json:"intent,omitempty"`                                                                               // 识别的意图类型
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // 时间戳（毫秒）
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据（如延迟、历史数量等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_xiaov_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *ChatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ========== 流式聊天响应 ==========
type ChatStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatStreamResponse_Content
	//	*ChatStreamResponse_Done
	//	*ChatStreamResponse_Error
	Payload       isChatStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamResponse) Reset() {
	*x = ChatStreamResponse{}
	mi := &file_proto_xiaov_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamResponse) ProtoMessage() {}

func (x *ChatStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{3}
}

func (x *ChatStreamResponse) GetPayload() isChatStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatStreamResponse) GetContent() *StreamContent {
	if x != nil {
		if x, ok := x.Payload.(*ChatStreamResponse_Content); ok {
			return x.Content
		}
	}
	return nil
}

func (x *ChatStreamResponse) GetDone() *StreamDone {
	if x != nil {
		if x, ok := x.Payload.(*ChatStreamResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ChatStreamResponse) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Payload.(*ChatStreamResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isChatStreamResponse_Payload interface {
	isChatStreamResponse_Payload()
}

type ChatStreamResponse_Content struct {
	Content *StreamContent `protobuf:"bytes,1,opt,name=content,proto3,oneof"` // 内容片段
}

type ChatStreamResponse_Done struct {
	Done *StreamDone `protobuf:"bytes,2,opt,name=done,proto3,oneof"` // 完成标记
}

type ChatStreamResponse_Error struct {
	Error *StreamError `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // 错误信息
}

func (*ChatStreamResponse_Content) isChatStreamResponse_Payload() {}

func (*ChatStreamResponse_Done) isChatStreamResponse_Payload() {}

func (*ChatStreamResponse_Error) isChatStreamResponse_Payload() {}

type StreamContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                      // 内容片段
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Intent        string                 `protobuf:"bytes,3,opt,name=intent,proto3" json:"intent,omitempty"`                        // 意图类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContent) Reset() {
	*x = StreamContent{}
	mi := &file_proto_xiaov_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContent) ProtoMessage() {}

func (x *StreamContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContent.ProtoReflect.Descriptor instead.
func (*StreamContent) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{4}
}

func (x *StreamContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamContent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamContent) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

type StreamDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Intent        string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`                        // 意图类型
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 完成时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDone) Reset() {
	*x = StreamDone{}
	mi := &file_proto_xiaov_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDone) ProtoMessage() {}

func (x *StreamDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDone.ProtoReflect.Descriptor instead.
func (*StreamDone) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{5}
}

func (x *StreamDone) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamDone) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *StreamDone) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 错误信息
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_proto_xiaov_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{6}
}

func (x *StreamError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamError) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ========== 获取会话历史 ==========
type GetSessionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID（必填）
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                         // 返回记录数量限制（默认20，最大100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionHistoryRequest) Reset() {
	*x = GetSessionHistoryRequest{}
	mi := &file_proto_xiaov_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionHistoryRequest) ProtoMessage() {}

func (x *GetSessionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSessionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSessionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"` // 历史消息列表
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`      // 总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionHistoryResponse) Reset() {
	*x = GetSessionHistoryResponse{}
	mi := &file_proto_xiaov_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionHistoryResponse) ProtoMessage() {}

func (x *GetSessionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetSessionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionHistoryResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSessionHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSessionHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetSessionHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // 消息ID
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                        // 会话ID
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                 // 用户ID
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`                                                                                   // 角色：user/assistant
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 消息内容
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // 时间戳
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_xiaov_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ========== 清空会话 ==========
type ClearSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSessionRequest) Reset() {
	*x = ClearSessionRequest{}
	mi := &file_proto_xiaov_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSessionRequest) ProtoMessage() {}

func (x *ClearSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSessionRequest.ProtoReflect.Descriptor instead.
func (*ClearSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{10}
}

func (x *ClearSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ClearSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cleared       bool                   `protobuf:"varint,3,opt,name=cleared,proto3" json:"cleared,omitempty"` // 是否成功清空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSessionResponse) Reset() {
	*x = ClearSessionResponse{}
	mi := &file_proto_xiaov_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSessionResponse) ProtoMessage() {}

func (x *ClearSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSessionResponse.ProtoReflect.Descriptor instead.
func (*ClearSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{11}
}

func (x *ClearSessionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClearSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClearSessionResponse) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

// ========== 健康检查 ==========
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_xiaov_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{12}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`        // 状态：healthy/unhealthy
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`      // 版本号
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	Features      []string               `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty"`    // 支持的功能列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_xiaov_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xiaov_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_xiaov_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_proto_xiaov_proto protoreflect.FileDescriptor

const file_proto_xiaov_proto_rawDesc = "" +
	"\n" +
	"\x11proto/xiaov.proto\x12\axiaovpb\"<\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\vChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xa5\x02\n" +
	"\fChatResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06intent\x18\x05 \x01(\tR\x06intent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.xiaovpb.ChatResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x12ChatStreamResponse\x122\n" +
	"\acontent\x18\x01 \x01(\v2\x16.xiaovpb.StreamContentH\x00R\acontent\x12)\n" +
	"\x04done\x18\x02 \x01(\v2\x13.xiaovpb.StreamDoneH\x00R\x04done\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x14.xiaovpb.StreamErrorH\x00R\x05errorB\t\n" +
	"\apayload\"`\n" +
	"\rStreamContent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06intent\x18\x03 \x01(\tR\x06intent\"a\n" +
	"\n" +
	"StreamDone\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"Z\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"O\n" +
	"\x18GetSessionHistoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x91\x01\n" +
	"\x19GetSessionHistoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\bmessages\x18\x03 \x03(\v2\x14.xiaovpb.ChatMessageR\bmessages\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\x9e\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12>\n" +
	"\bmetadata\x18\a \x03(\v2\".xiaovpb.ChatMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x13ClearSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"^\n" +
	"\x14ClearSessionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\acleared\x18\x03 \x01(\bR\acleared\"\x14\n" +
	"\x12HealthCheckRequest\"\x95\x01\n" +
	"\x13HealthCheckResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bfeatures\x18\x05 \x03(\tR\bfeatures2\xf9\x02\n" +
	"\fXiaovService\x123\n" +
	"\x04Chat\x12\x14.xiaovpb.ChatRequest\x1a\x15.xiaovpb.ChatResponse\x12A\n" +
	"\n" +
	"ChatStream\x12\x14.xiaovpb.ChatRequest\x1a\x1b.xiaovpb.ChatStreamResponse0\x01\x12Z\n" +
	"\x11GetSessionHistory\x12!.xiaovpb.GetSessionHistoryRequest\x1a\".xiaovpb.GetSessionHistoryResponse\x12K\n" +
	"\fClearSession\x12\x1c.xiaovpb.ClearSessionRequest\x1a\x1d.xiaovpb.ClearSessionResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.xiaovpb.HealthCheckRequest\x1a\x1c.xiaovpb.HealthCheckResponseB/Z-github.com/vision_world/video_agent/proto_genb\x06proto3"

var (
	file_proto_xiaov_proto_rawDescOnce sync.Once
	file_proto_xiaov_proto_rawDescData []byte
)

func file_proto_xiaov_proto_rawDescGZIP() []byte {
	file_proto_xiaov_proto_rawDescOnce.Do(func() {
		file_proto_xiaov_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_xiaov_proto_rawDesc), len(file_proto_xiaov_proto_rawDesc)))
	})
	return file_proto_xiaov_proto_rawDescData
}

var file_proto_xiaov_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_xiaov_proto_goTypes = []any{
	(*BaseResponse)(nil),              // 0: xiaovpb.BaseResponse
	(*ChatRequest)(nil),               // 1: xiaovpb.ChatRequest
	(*ChatResponse)(nil),              // 2: xiaovpb.ChatResponse
	(*ChatStreamResponse)(nil),        // 3: xiaovpb.ChatStreamResponse
	(*StreamContent)(nil),             // 4: xiaovpb.StreamContent
	(*StreamDone)(nil),                // 5: xiaovpb.StreamDone
	(*StreamError)(nil),               // 6: xiaovpb.StreamError
	(*GetSessionHistoryRequest)(nil),  // 7: xiaovpb.GetSessionHistoryRequest
	(*GetSessionHistoryResponse)(nil), // 8: xiaovpb.GetSessionHistoryResponse
	(*ChatMessage)(nil),               // 9: xiaovpb.ChatMessage
	(*ClearSessionRequest)(nil),       // 10: xiaovpb.ClearSessionRequest
	(*ClearSessionResponse)(nil),      // 11: xiaovpb.ClearSessionResponse
	(*HealthCheckRequest)(nil),        // 12: xiaovpb.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 13: xiaovpb.HealthCheckResponse
	nil,                               // 14: xiaovpb.ChatResponse.MetadataEntry
	nil,                               // 15: xiaovpb.ChatMessage.MetadataEntry
}
var file_proto_xiaov_proto_depIdxs = []int32{
	14, // 0: xiaovpb.ChatResponse.metadata:type_name -> xiaovpb.ChatResponse.MetadataEntry
	4,  // 1: xiaovpb.ChatStreamResponse.content:type_name -> xiaovpb.StreamContent
	5,  // 2: xiaovpb.ChatStreamResponse.done:type_name -> xiaovpb.StreamDone
	6,  // 3: xiaovpb.ChatStreamResponse.error:type_name -> xiaovpb.StreamError
	9,  // 4: xiaovpb.GetSessionHistoryResponse.messages:type_name -> xiaovpb.ChatMessage
	15, // 5: xiaovpb.ChatMessage.metadata:type_name -> xiaovpb.ChatMessage.MetadataEntry
	1,  // 6: xiaovpb.XiaovService.Chat:input_type -> xiaovpb.ChatRequest
	1,  // 7: xiaovpb.XiaovService.ChatStream:input_type -> xiaovpb.ChatRequest
	7,  // 8: xiaovpb.XiaovService.GetSessionHistory:input_type -> xiaovpb.GetSessionHistoryRequest
	10, // 9: xiaovpb.XiaovService.ClearSession:input_type -> xiaovpb.ClearSessionRequest
	12, // 10: xiaovpb.XiaovService.HealthCheck:input_type -> xiaovpb.HealthCheckRequest
	2,  // 11: xiaovpb.XiaovService.Chat:output_type -> xiaovpb.ChatResponse
	3,  // 12: xiaovpb.XiaovService.ChatStream:output_type -> xiaovpb.ChatStreamResponse
	8,  // 13: xiaovpb.XiaovService.GetSessionHistory:output_type -> xiaovpb.GetSessionHistoryResponse
	11, // 14: xiaovpb.XiaovService.ClearSession:output_type -> xiaovpb.ClearSessionResponse
	13, // 15: xiaovpb.XiaovService.HealthCheck:output_type -> xiaovpb.HealthCheckResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_xiaov_proto_init() }
func file_proto_xiaov_proto_init() {
	if File_proto_xiaov_proto != nil {
		return
	}
	file_proto_xiaov_proto_msgTypes[3].OneofWrappers = []any{
		(*ChatStreamResponse_Content)(nil),
		(*ChatStreamResponse_Done)(nil),
		(*ChatStreamResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_xiaov_proto_rawDesc), len(file_proto_xiaov_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_xiaov_proto_goTypes,
		DependencyIndexes: file_proto_xiaov_proto_depIdxs,
		MessageInfos:      file_proto_xiaov_proto_msgTypes,
	}.Build()
	File_proto_xiaov_proto = out.File
	file_proto_xiaov_proto_goTypes = nil
	file_proto_xiaov_proto_depIdxs = nil
}
