// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.1
// source: proto/xiaov.proto

package proto_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	XiaovService_Chat_FullMethodName              = "/xiaovpb.XiaovService/Chat"
	XiaovService_ChatStream_FullMethodName        = "/xiaovpb.XiaovService/ChatStream"
	XiaovService_GetSessionHistory_FullMethodName = "/xiaovpb.XiaovService/GetSessionHistory"
	XiaovService_ClearSession_FullMethodName      = "/xiaovpb.XiaovService/ClearSession"
	XiaovService_HealthCheck_FullMethodName       = "/xiaovpb.XiaovService/HealthCheck"
)

// XiaovServiceClient is the client API for XiaovService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XiaovServiceClient interface {
	// 发送消息并获取回复（普通模式）
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// 发送消息并获取流式回复（SSE模式）
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (XiaovService_ChatStreamClient, error)
	// 获取会话历史记录
	GetSessionHistory(ctx context.Context, in *GetSessionHistoryRequest, opts ...grpc.CallOption) (*GetSessionHistoryResponse, error)
	// 清空会话历史
	ClearSession(ctx context.Context, in *ClearSessionRequest, opts ...grpc.CallOption) (*ClearSessionResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type xiaovServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXiaovServiceClient(cc grpc.ClientConnInterface) XiaovServiceClient {
	return &xiaovServiceClient{cc}
}

func (c *xiaovServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, XiaovService_Chat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xiaovServiceClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (XiaovService_ChatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &XiaovService_ServiceDesc.Streams[0], XiaovService_ChatStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &xiaovServiceChatStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type XiaovService_ChatStreamClient interface {
	Recv() (*ChatStreamResponse, error)
	grpc.ClientStream
}

type xiaovServiceChatStreamClient struct {
	grpc.ClientStream
}

func (x *xiaovServiceChatStreamClient) Recv() (*ChatStreamResponse, error) {
	m := new(ChatStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *xiaovServiceClient) GetSessionHistory(ctx context.Context, in *GetSessionHistoryRequest, opts ...grpc.CallOption) (*GetSessionHistoryResponse, error) {
	out := new(GetSessionHistoryResponse)
	err := c.cc.Invoke(ctx, XiaovService_GetSessionHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xiaovServiceClient) ClearSession(ctx context.Context, in *ClearSessionRequest, opts ...grpc.CallOption) (*ClearSessionResponse, error) {
	out := new(ClearSessionResponse)
	err := c.cc.Invoke(ctx, XiaovService_ClearSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xiaovServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, XiaovService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XiaovServiceServer is the server API for XiaovService service.
// All implementations must embed UnimplementedXiaovServiceServer
// for forward compatibility
type XiaovServiceServer interface {
	// 发送消息并获取回复（普通模式）
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// 发送消息并获取流式回复（SSE模式）
	ChatStream(*ChatRequest, XiaovService_ChatStreamServer) error
	// 获取会话历史记录
	GetSessionHistory(context.Context, *GetSessionHistoryRequest) (*GetSessionHistoryResponse, error)
	// 清空会话历史
	ClearSession(context.Context, *ClearSessionRequest) (*ClearSessionResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedXiaovServiceServer()
}

// UnimplementedXiaovServiceServer must be embedded to have forward compatible implementations.
type UnimplementedXiaovServiceServer struct {
}

func (UnimplementedXiaovServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedXiaovServiceServer) ChatStream(*ChatRequest, XiaovService_ChatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedXiaovServiceServer) GetSessionHistory(context.Context, *GetSessionHistoryRequest) (*GetSessionHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionHistory not implemented")
}
func (UnimplementedXiaovServiceServer) ClearSession(context.Context, *ClearSessionRequest) (*ClearSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearSession not implemented")
}
func (UnimplementedXiaovServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedXiaovServiceServer) mustEmbedUnimplementedXiaovServiceServer() {}

// UnsafeXiaovServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XiaovServiceServer will
// result in compilation errors.
type UnsafeXiaovServiceServer interface {
	mustEmbedUnimplementedXiaovServiceServer()
}

func RegisterXiaovServiceServer(s grpc.ServiceRegistrar, srv XiaovServiceServer) {
	s.RegisterService(&XiaovService_ServiceDesc, srv)
}

func _XiaovService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XiaovServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XiaovService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XiaovServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XiaovService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XiaovServiceServer).ChatStream(m, &xiaovServiceChatStreamServer{stream})
}

type XiaovService_ChatStreamServer interface {
	Send(*ChatStreamResponse) error
	grpc.ServerStream
}

type xiaovServiceChatStreamServer struct {
	grpc.ServerStream
}

func (x *xiaovServiceChatStreamServer) Send(m *ChatStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _XiaovService_GetSessionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XiaovServiceServer).GetSessionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XiaovService_GetSessionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XiaovServiceServer).GetSessionHistory(ctx, req.(*GetSessionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XiaovService_ClearSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XiaovServiceServer).ClearSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XiaovService_ClearSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XiaovServiceServer).ClearSession(ctx, req.(*ClearSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XiaovService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XiaovServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XiaovService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XiaovServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XiaovService_ServiceDesc is the grpc.ServiceDesc for XiaovService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XiaovService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xiaovpb.XiaovService",
	HandlerType: (*XiaovServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _XiaovService_Chat_Handler,
		},
		{
			MethodName: "GetSessionHistory",
			Handler:    _XiaovService_GetSessionHistory_Handler,
		},
		{
			MethodName: "ClearSession",
			Handler:    _XiaovService_ClearSession_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _XiaovService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _XiaovService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/xiaov.proto",
}
